### ISSUE TITLE
objkt id bottleneck

### ISSUE THREAD

**Issue by crzypatchwork** [hicetnunc2000/hicetnunc-api#2]

**Comment by anonymoussprocket** [comment]
👍🏻

**Comment by crzypatchwork** [comment]
we have currently two bottle necks:

- objkt id: we have not been able yet to set a proper indexer to query the whole big map with all tokens. we'd like to find a way to optimize such search and gather information, retrieving metadata, swaps, owners and hDAO balance. (possibly transactional history as well.
- collections: with the help of cryptonomic.tech we were able to retrieve a user creation really fast for the /tz/<address> path. but we have not been able to retrieve one's whole collection. In this case we just need base information as objkt id and token metadata.

FA2 standard bug: a user with 0 balance remains in the big map?

**Comment by crzypatchwork** [comment]
objkts https://better-call.dev/mainnet/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/operations
hDAO https://better-call.dev/mainnet/KT1AFA2mwNUMNd4SsujE1YYp29vd8BZejyKW

**Comment by AndreasGassmann** [comment]
For TzColors, we basically pull the bigmap of the FA2 token, as well as the auction house contract. Together, we can determine who is the owner and which auctions are currently open. So on every initial page load, we load the full bigmap on the client and do the calculations there. After that it just gets the latest changes and applies it to the frontend state.

With conseil, you might be able to filter things server side do not every user has to load the full state.

**Comment by crzypatchwork** [comment]
yes registering changes would be interesting. what do you people think on have .owl for querying those in the future?
