### ISSUE TITLE
What does .setLimit(collectionQuery, 20_000) do?

### ISSUE THREAD

**Issue by Quasimondo** [hicetnunc2000/hicetnunc-api#20]
I am trying to do a test install of the API on a server, but it triggers an "unknown token" error at these lines:

`collectionQuery = conseiljs.ConseilQueryBuilder.setLimit(collectionQuery, 20_000)`

Is this a special number format that requires some additonal setup or configuration? Can I replace this with some other regular numeric value that does not trigger an error?

**Comment by anonymoussprocket** [comment]
It limits the number of result rows to 20k.

**Comment by skenaja** [comment]
@Quasimondo I hit this error, but it was due to the default version of node installed on my machine which didn't recognise the use of `_` as a numeric separator. I used `nvm` to switch to using version 12.20.1 as per package.json which removed the error

**Comment by Quasimondo** [comment]
Ah thanks for that! I am not using node a lot, so it didn't even occur to me that that's the cause.
