### ISSUE TITLE
OBJKTs on `o.json` should be filtered from `/tz` results

### ISSUE THREAD

**Issue by skenaja** [hicetnunc2000/hicetnunc-api#55]
See https://github.com/hicetnunc2000/hicetnunc/issues/520 for a detailed description.

You wouldn't want to return http 410 for the whole account for this instance, just filter out the "bad" token.

Longer-term, OBJKTs with invalid ipfs token_info schema could probably be checked using something like `json-schema`.

**Comment by crzypatchwork** [comment]
yes another possibility is to have a CA or other validation process
